# Generated by Django 2.1.1 on 2018-10-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('about', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=254)),
                ('date', models.DateField()),
                ('pagetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.PageType')),
            ],
        ),
    ]
