# Generated by Django 2.1.1 on 2018-10-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='official',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
