# Generated by Django 2.1.3 on 2018-11-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_webpage_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetype',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
