# Generated by Django 2.1.3 on 2018-11-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20181128_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='creator',
        ),
    ]
