# Generated by Django 2.1.3 on 2019-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_remove_webpage_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='about',
            field=models.CharField(max_length=2048),
        ),
    ]
